package: naju_newsmanager
version: '0.0.3'
author: NAJU Sachsen
supportpage: https://github.com/NAJU-Sachsen/rex-newsmanager
requires:
  redaxo: '>=5.10'
  php: '>=7.1'
  packages:
    naju_group_accounts: '>=0.0.1'
    redactor2: '>=4.0.0'
    cronjob: '>=2.7.0'
page:
  title: 'Blogs'
  icon: rex-icon fa-newspaper-o
  subpages:
    list:
      title: 'Beiträge'
    compose:
      title: 'Verfassen'
    blogs:
      title: 'Blogs'